[package]
name = "LMSM"
version = "1.0.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
winres = "0.1"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
